### ISSUE TITLE
Can no longer connect to LoRa E5-Mini board after debug

### ISSUE THREAD

**Issue by dotdm26** [androbi-com/STM32WLE5JC-Blinky-StopMode#1]
Hi, androbi-com. I'm an IT student who happens to be doing a personal IoT project that involves using LoRa E5 mini boards.

I was looking around for examples on how to program the board in order to hook it up with the sensors, and I came across this repository of yours. I wanted to see how your code would work in order for me to figure out how to utilize its pins, as I am still inexperienced in embedded programming.

Your program seems to work fine, but afterwards I was unable to debug my board, which refuses to connect via ST-Link. I intended to perform a Full Chip Erase on the board, but now I also can no longer connect my board to STM32CubeProgrammer. I keep getting the error "No STM32 Target Found", despite having tried to set the mode to SWD -> "Connect Under Reset" before holding the reset button and pressing Connect. 

I was wondering if you have come across this kind of issue before, and I would like to know whether you were able to fix it. 
I noticed that you had configured the pins in the .ioc file and I thought maybe it played a role in causing the problem I have, but please correct me if I'm wrong.

Best regards,
Minh Do

**Comment by dotdm26** [comment]
I've managed to fix the problem, I connected my board to another PC, this time the CubeProgrammer successfully managed to erase the chip and I was able to debug the board again. Apologies for wasting your time!

**Comment by albper** [comment]
I had exactly the same problem and I have solved it with your comments.

Thank you. It wasn't a waste of time.

I can't understand why changing the computer solves the problem.
